export default {
    LOAD_COUNTIES_ATTEMPT: 'LOAD_COUNTIES_ATTEMPT',
    LOAD_COUNTIES_SUCCESS: 'LOAD_COUNTIES_SUCCESS',
    LOAD_COUNTIES_FAILURE: 'LOAD_COUNTIES_FAILURE',

    SELECT_MUNICIPALITY: 'SELECT_MUNICIPALITY',

    LOAD_KINDERGARTENS_ATTEMPT: 'LOAD_KINDERGARTENS_ATTEMPT',
    LOAD_KINDERGARTENS_SUCCESS: 'LOAD_KINDERGARTENS_SUCCESS',
    LOAD_KINDERGARTENS_FAILURE: 'LOAD_KINDERGARTENS_FAILURE',

    LOAD_KINDERGARTEN_DETAILS_ATTEMPT: 'LOAD_KINDERGARTEN_DETAILS_ATTEMPT',
    LOAD_KINDERGARTEN_DETAILS_SUCCESS: 'LOAD_KINDERGARTEN_DETAILS_SUCCESS',
    LOAD_KINDERGARTEN_DETAILS_FAILURE: 'LOAD_KINDERGARTEN_DETAILS_FAILURE'
}